#!/bin/sh
#
# @name AMOV quad X Using NDI SITL
#
# @type Quadrotor x
#
# @maintainer Wenxuan Gao <jyz_john@sjtu.edu.cn>
#

. ${R}etc/init.d/rc.mc_defaults

param set-default SYS_CTRL_ALLOC 1

param set-default MC_MASS 1.37
param set-default MC_IXX 0.0108
param set-default MC_IYY 0.0115
param set-default MC_IZZ 0.0175

param set-default MC_PITCHRATE_K 1
param set-default MC_ROLLRATE_K 1

param set-default MC_PITCHRATE_P 0.1
param set-default MC_PITCHRATE_I 0.05
param set-default MC_PITCHRATE_D 0.0001
param set-default MC_ROLLRATE_P 0.1
param set-default MC_ROLLRATE_I 0.05
param set-default MC_ROLLRATE_D 0.0001

param set-default CA_AIRFRAME 0

param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 0.15
param set-default CA_ROTOR0_PY 0.145
param set-default CA_ROTOR0_KM 0.0162
param set-default CA_ROTOR1_PX -0.15
param set-default CA_ROTOR1_PY -0.145
param set-default CA_ROTOR1_KM 0.0162
param set-default CA_ROTOR2_PX 0.15
param set-default CA_ROTOR2_PY -0.145
param set-default CA_ROTOR2_KM -0.0162
param set-default CA_ROTOR3_PX -0.15
param set-default CA_ROTOR3_PY 0.145
param set-default CA_ROTOR3_KM -0.0162

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104

set MIXER skip
set MIXER_AUX none

# set MIXER quad_x
