#!/bin/sh
#
# @name Standard VTOL
#
# @type Standard VTOL
#

. ${R}etc/init.d/rc.vtol_defaults

param set-default MAV_TYPE 22
param set-default SYS_CTRL_ALLOC 1
param set-default CA_AIRFRAME 2

param set-default CA_ROTOR_COUNT 5
param set-default CA_ROTOR0_PX 0.63
param set-default CA_ROTOR0_PY 0.455
param set-default CA_ROTOR0_KM 0.0298
param set-default CA_ROTOR1_PX -0.76
param set-default CA_ROTOR1_PY -0.455
param set-default CA_ROTOR1_KM 0.0298
param set-default CA_ROTOR2_PX 0.63
param set-default CA_ROTOR2_PY -0.455
param set-default CA_ROTOR2_KM -0.0298
param set-default CA_ROTOR3_PX -0.76
param set-default CA_ROTOR3_PY 0.455
param set-default CA_ROTOR3_KM -0.0298
param set-default CA_ROTOR4_AX 1.0
param set-default CA_ROTOR4_AZ 0.0
param set-default CA_ROTOR4_PX -0.54
param set-default CA_ROTOR4_PZ 0.025
param set-default CA_ROTOR4_KM -0.01
param set-default CA_ROTOR0_CT 92.7
param set-default CA_ROTOR1_CT 92.7
param set-default CA_ROTOR2_CT 92.7
param set-default CA_ROTOR3_CT 92.7
param set-default CA_ROTOR4_CT 112.7

param set-default CA_SV_CS_COUNT 4
param set-default CA_SV_CS0_TYPE 1
param set-default CA_SV_CS0_TRQ_R -0.5
param set-default CA_SV_CS1_TYPE 2
param set-default CA_SV_CS1_TRQ_R 0.5
param set-default CA_SV_CS2_TYPE 3
param set-default CA_SV_CS2_TRQ_P 1.0
param set-default CA_SV_CS3_TYPE 4
param set-default CA_SV_CS3_TRQ_Y 1.0
param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default PWM_MAIN_FUNC5 105
param set-default PWM_MAIN_FUNC6 201
param set-default PWM_MAIN_FUNC7 202
param set-default PWM_MAIN_FUNC8 203
param set-default PWM_MAIN_FUNC9 204

param set-default FW_L1_PERIOD 12
param set-default FW_MAN_P_MAX 30
param set-default FW_PR_FF 0.2
param set-default FW_PR_P 0.9
param set-default FW_PSP_OFF 2
param set-default FW_R_LIM 30
param set-default FW_P_LIM_MAX 20
param set-default FW_P_LIM_MIN -20
param set-default FW_RR_FF 0.1
param set-default FW_RR_P 0.3

param set-default FW_THR_CRUISE 0.5
param set-default FW_THR_MAX 1.0
param set-default FW_THR_MIN 0.05
param set-default FW_AIRSPD_MAX 36
param set-default FW_AIRSPD_MIN 20
param set-default FW_AIRSPD_STALL 18
param set-default FW_AIRSPD_TRIM 25
param set-default FW_T_CLMB_MAX 5.0
param set-default FW_T_SINK_MAX 5.0
param set-default FW_T_SINK_MIN 2.0

param set-default MC_ROLL_P 8.0
param set-default MC_PITCH_P 8.0
param set-default MC_YAW_P 4.0
param set-default MC_ROLLRATE_P 0.6
param set-default MC_PITCHRATE_P 0.6
param set-default MC_YAWRATE_P 0.6
param set-default MC_ROLLRATE_I 0.1
param set-default MC_PITCHRATE_I 0.1
param set-default MC_YAWRATE_I 0.1

param set-default MIS_TAKEOFF_ALT 50
param set-default MPC_TKO_RAMP_T 1

param set-default MPC_ACC_HOR_MAX 2
param set-default MPC_XY_P 0.8
param set-default MPC_XY_VEL_P_ACC 3
param set-default MPC_XY_VEL_I_ACC 4
param set-default MPC_XY_VEL_D_ACC 0.1

param set-default NAV_ACC_RAD 5

param set-default VT_FWD_THRUST_EN 0
param set-default VT_F_TRANS_THR 1.0
param set-default VT_ARSP_BLEND 18
param set-default VT_ARSP_TRANS 20
param set-default VT_MOT_ID 1234
param set-default VT_FW_MOT_OFFID 1234
param set-default VT_B_TRANS_DUR 10
param set-default VT_TYPE 2

# set MIXER_FILE etc/mixers-sitl/standard_vtol_sitl.main.mix
# set MIXER custom

set MIXER skip
set MIXER_AUX none
